name: Laravel-lang
slogan: Internationalization of Laravel
url: http://caouecs.github.io/Laravel-lang/
title: Laravel-lang
description: List of languages for Laravel
show_downloads: true
theme: jekyll-theme-midnight
